### ISSUE TITLE
Parking owner features

### ISSUE THREAD

**Issue by logansmith283** [colewebb/group-8#14] opened 2021-02-28 06:53 UTC
Parking owners will have access to a page to add lots and to manage lots.
When adding lots, an address is required, and details such as number of spots available and price will be added. 
When managing existing lots, number of spots may be changed, or price may be changed.
Different sized spots can be listed in separate sections, and will be numbered separately from other sections.
Prices will be split 75/25 with the lot owners and the university.

Lot owners will have all the privileges of a parking attendant.
Lot owners will have ability to appoint other users as lot attendants, and manage their attendants.

**Comment by colewebb** [comment] 2021-03-26 01:37
Duplicate of #40

**Closed** 2021-04-22 02:23 UTC
Labels: feature
